"""
Shared fixtures for E2E tests — Prompt 9A / 9B.

Provides a session-scoped seeded database and mock AI provider
so that all E2E tests share one data-seeding pass.
"""

import asyncio
import os
import sys
import shutil

import pytest
import pytest_asyncio

# Ensure backend is on sys.path
BACKEND_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "backend"
)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, BACKEND_DIR)
sys.path.insert(0, PROJECT_ROOT)


@pytest.fixture(scope="session")
def event_loop():
    """Create a single event loop for the entire test session."""
    loop = asyncio.new_event_loop()
    yield loop
    loop.close()


@pytest_asyncio.fixture(scope="session")
async def seeded_env():
    """
    Session-scoped fixture that:
    1. Creates an isolated SQLite database with all dummy data.
    2. Overrides the vector store and file storage paths.
    3. Returns the DummyDataSeeder instance with all entity IDs.
    """
    from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession

    # Paths for isolated test environment
    test_dir = os.path.join(PROJECT_ROOT, ".e2e_test_workspace")
    db_path = os.path.join(test_dir, "e2e_test.db")
    vector_path = os.path.join(test_dir, "vectors")
    storage_path = os.path.join(test_dir, "storage")

    # Clean slate
    if os.path.exists(test_dir):
        shutil.rmtree(test_dir)
    os.makedirs(test_dir, exist_ok=True)

    db_url = f"sqlite+aiosqlite:///{db_path}"

    # Override settings BEFORE importing anything that reads them at module level
    from core.config import get_settings
    settings = get_settings()
    settings.vector_store_path = vector_path
    settings.file_storage_path = storage_path

    # Import and run seeder
    from scripts.seed_dummy_data import DummyDataSeeder
    seeder = DummyDataSeeder(db_url, vector_path, storage_path)
    summary = await seeder.seed_all()

    # Store summary on the seeder for test access
    seeder.summary = summary
    seeder.db_url = db_url
    seeder.test_dir = test_dir

    yield seeder

    # Cleanup after all tests
    if os.path.exists(test_dir):
        shutil.rmtree(test_dir)


@pytest_asyncio.fixture(scope="session")
async def db_session(seeded_env):
    """
    Provides a read-only async session to the seeded test database.
    """
    from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession

    engine = create_async_engine(seeded_env.db_url, echo=False)
    session_factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with session_factory() as session:
        yield session

    await engine.dispose()


@pytest.fixture(scope="session")
def mock_provider():
    """
    Returns the deterministic mock AI provider instance.
    """
    from scripts.mock_ai_provider import MockAIProvider
    return MockAIProvider()


# ═══════════════════════════════════════════════════════════════════
# Shared verification results store + report generator
# ═══════════════════════════════════════════════════════════════════

# Module-level dict shared across all test modules in this conftest scope
from tests.e2e.shared_state import VERIFICATION_RESULTS


@pytest.fixture(scope="session")
def verification_results():
    """Provides a shared dict for verification checks to store results."""
    return VERIFICATION_RESULTS


def pytest_sessionfinish(session, exitstatus):
    """
    Generates docs/verification_report.md with concrete evidence from each check.
    Runs after all tests complete.
    """
    if not VERIFICATION_RESULTS:
        return

    docs_dir = os.path.join(PROJECT_ROOT, "docs")
    os.makedirs(docs_dir, exist_ok=True)
    report_path = os.path.join(docs_dir, "verification_report.md")

    lines = [
        "# Verification Report — Prompt 9B",
        "",
        "Auto-generated by `test_verification_checks.py`.",
        "",
        "---",
        "",
    ]

    check_names = {
        "permission_dept_no_project": "CHECK 1a: Permission — Dept Access, No Project Membership",
        "permission_insufficient_clearance": "CHECK 1b: Permission — Insufficient Classification Clearance",
        "chunking_table_extraction": "CHECK 2: Chunking — Table/Multi-Column Extraction",
        "reranking_order_change": "CHECK 3: Retrieval/Reranking — Order Change Proof",
        "confidence_gap": "CHECK 4: Confidence/Abstention — Score Gap",
        "citation_accuracy": "CHECK 5: Citation Accuracy — Zero Hallucinated Citations",
    }

    for key, title in check_names.items():
        data = VERIFICATION_RESULTS.get(key, {})
        passed = data.get("pass", "N/A")
        status_str = "✅ PASS" if passed is True else ("❌ FAIL" if passed is False else "⚠️ N/A")

        lines.append(f"## {title}")
        lines.append("")
        lines.append(f"**Result: {status_str}**")
        lines.append("")
        lines.append("| Field | Value |")
        lines.append("|-------|-------|")
        for field, value in data.items():
            if field == "pass":
                continue
            lines.append(f"| {field} | `{value}` |")
        lines.append("")
        lines.append("---")
        lines.append("")

    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\n[OK] Verification report written to: {report_path}")

